### ISSUE TITLE
Precompute accelerations and Newtonian potentials

### ISSUE THREAD

**Issue by PerezHz** [PerezHz/NEOs.jl#17]
This issue follows from an offline discussion with @lbenet and @LuEdRaMo. Currently, before performing a propagation, we use `loadeph` to precompute the accelerations and the Newtonian potentials of the perturbers (planets, asteroid, etc.) of a NEO orbit, besides changing the units of the ephemeris themselves from km and km/sec to au, au/day. But now we have `NEOs.sseph`, which would allow us to precompute these things, so that their computation can be taken out from the integration loop. This can help simplify code (and maybe improve performance?).

**Comment by LuEdRaMo** [comment]
As a reference, the files we need to have precomputed accelerations and Newtonian potentials as artifacts are: 
- 100 years Solar System integration (556 MB).
- corresponding accelerations (257 MB).
- corresponding Newtonian potentials (86 MB)

Together, they fit within the 1GB of free Github LFS.

**Comment by LuEdRaMo** [comment]
Currently, `NEOs.sseph` has time in seconds but we convert to days for the integration. Should we skip this conversion by saving `NEOs.sseph` in days in the first place?

**Comment by PerezHz** [comment]
> Currently, NEOs.sseph has time in seconds but we convert to days for the integration. Should we skip this conversion by saving NEOs.sseph in days in the first place?

Thank you @LuEdRaMo for checking this, it's great news that we can fit everything within the available GitHub LFS space 😅! And yeah, I agree we should save `NEOs.sseph` in au, au/day, although then we have to be careful when computing observables, since we are now assuming that they read ET seconds since J2000 and ouput pos. and vel., resp., in km and km/sec.

**Comment by PerezHz** [comment]
I would propose to first push #15 and #16 over the finish line and then tackle this.

**Comment by PerezHz** [comment]
Fixed by #25.
