### ISSUE TITLE
Avoid type piracy of `SatelliteToolboxTransformations.jl` overloads

### ISSUE THREAD

**Issue by PerezHz** [PerezHz/NEOs.jl#30]
Currently, here:
https://github.com/PerezHz/NEOs.jl/blob/7e0ceec3e2eeea03679d9b8140432baeeafd09a0/src/observations/topocentric.jl#L42
and here:
https://github.com/PerezHz/NEOs.jl/blob/7e0ceec3e2eeea03679d9b8140432baeeafd09a0/src/observations/topocentric.jl#L59
we are overloading methods defined in `SatelliteToolboxTransformations.jl` to be able to differentiate through those functions using `TaylorSeries` `Taylor1` and `TaylorN`; which is type piracy. It's not terrible, but I think we should try to avoid it. AFAIU, this is due to products of `StaticArray.SMatrix` with vectors of `<:AbstractSeries` sometimes giving `Vector{Any}` as a result, which is why the results of such products are type annotated in the overloaded methods here. Probably this issue belongs in `TaylorSeries`, but thought of opening this issue here to discuss and see how we might solve this.

**Comment by lbenet** [comment]
A way to overcome this (weak) type piracy would be to pass a `TaylorInterpolant`... Does this make sense?

Incidentally, have you looked to `Aqua.jl`? It may be worth...

**Comment by PerezHz** [comment]
Solved by JuliaDiff/TaylorSeries.jl#353
